### ISSUE TITLE
no module named Keras 

### ISSUE THREAD

**Issue by moshir** [antonpaquin/Tensorflow-Lambda-Layer#1]
Hi,
Nice work ! 
However, was not able to get import keras to work ...
Seems your test is only hcecking for tensorflow and numpy, but not keras ...

In the handler :
```
import tensorflow 
import keras
```

Error returned form AWS lambda : 
 ```
Unable to import module 'lambda_function': No module named 'keras'
```

**Comment by antonpaquin** [comment]
:man_facepalming: Thanks for the heads up, rebuilding now

**Comment by antonpaquin** [comment]
Should be fixed, and I've shared the layer as an ARN to avoid screwing around with zipfiles (`arn:aws:lambda:us-east-1:347034527139:layer:Tensorflow:3`)

**Comment by moshir** [comment]
Nice, this works like a charm !
Thx
